import { EXTENSION_DEFAULTS } from '../../constants';

export const DEFAULT_LOW_QUOTA_THRESHOLD_PERCENT: number = EXTENSION_DEFAULTS.DEFAULT_LOW_QUOTA_THRESHOLD_PERCENT;
export const DEFAULT_WEEKLY_QUOTA_PROTECTION_THRESHOLD_PERCENT: number = EXTENSION_DEFAULTS.DEFAULT_WEEKLY_QUOTA_PROTECTION_THRESHOLD_PERCENT;
export const DEFAULT_AUTO_SWITCH_TARGET = EXTENSION_DEFAULTS.DEFAULT_AUTO_SWITCH_TARGET;
export const GLOBAL_REFRESH_COOLDOWN_MS: number = EXTENSION_DEFAULTS.GLOBAL_REFRESH_COOLDOWN_MS;
export const ACCOUNT_REFRESH_COOLDOWN_MS: number = EXTENSION_DEFAULTS.ACCOUNT_REFRESH_COOLDOWN_MS;
export const OAUTH_COOLDOWN_MS: number = EXTENSION_DEFAULTS.OAUTH_COOLDOWN_MS;
export const IMPORT_COOLDOWN_MS: number = EXTENSION_DEFAULTS.IMPORT_COOLDOWN_MS;
